packageExtensions:
  react-cosmos@*:
    dependencies:
      react: "*"
      react-dom: "*"
    peerDependencies:
      react: "*"
      react-dom: "*" 
    peerDependenciesMeta:
      react: {
        optional: true
      }
  react-cosmos-core@*:
    dependencies:
      react: "*"
      react-dom: "*"
    peerDependencies:
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      react: {
        optional: true
      }
